### ISSUE TITLE
Clarify Code posting on Twitter 

### ISSUE THREAD

**Issue by cooknl** [rfordatascience/tidytuesday#1]
The readme states
> Include a copy of the code used to create your visualization when you post to Twitter.

Is there a preferred method? For example, tweet the graphic with the hash tag, then reply to your own tweet with a link? Or as a Twitter essay? Or as an attachment? If attachment, then as UTF-8 text file?

**Comment by cooknl** [comment]
I notice the Carbon reference. So, just an image of the code? That will limit reuse of good ideas, though, right?

**Comment by ellisvalentiner** [comment]
If the code is succinct then Carbon is a good choice but if the code is
long then link to your repo or Rmd file.

**Comment by cooknl** [comment]
Thanks!
