### ISSUE TITLE
possible #tidytuesday topic: student loans

### ISSUE THREAD

**Issue by apalbright** [rfordatascience/tidytuesday#138]
The [Dignity + Debt project](https://www.dignityanddebt.org/projects/student-debt-racial-disparities/) is running a contest for data visualizations, maps, etc. that portray student loan debt.  [Here are the contest + award details.](https://docs.google.com/forms/d/e/1FAIpQLSckHpk5xJwqW0_sIEnCs-tScxttMV5WVqGjP0Ws8bD0x_LZHA/viewform)

I figure this could make for a good tidy tuesday topic. Here are a few possible datasets that could be useful:

- the CFPB consumer complaint database [here](https://www.consumerfinance.gov/data-research/consumer-complaints/)
- default rates for federal student loans [here](https://studentaid.ed.gov/sa/about/data-center/student/default)

**Comment by jthomasmock** [comment]
Thanks!
