### ISSUE TITLE
Possible dataset: Data for Trails in the United States from the Rails-to-Trails Conservancy

### ISSUE THREAD

**Issue by jrosen48** [rfordatascience/tidytuesday#141]
I would like to submit a possible dataset for consideration for tidytuesday, on data for trails in the United States from the Rails-to-Trails Conservancy. I accessed the data via web-scraping and (minimally) cleaned it. it is available in the [**railtrails** package](https://github.com/jrosen48/railtrails). A brief description:

> Includes information (such as name, length, surface, reviews, and trailhead latitude and longitude) on 3,846 trails and 24,413 reviews in every state in the United States. 

The raw data is available [here](https://github.com/jrosen48/railtrails/tree/master/data), were it to be easier to open (here or through the package) and then to save it as a CSV. I'd also be happy to share it as a CSV, were it to be helpful.

**Comment by jthomasmock** [comment]
Ooh lovely! If you have a .csv that would be ideal, but the package is great too.

Thanks, this looks like a winner!

**Comment by jrosen48** [comment]
@jthomasmock unfortunately, folks at TrailLink.com have reached out asking for this data not to be shared, and so I'd like to put a pause on this right now.
