### ISSUE TITLE
Possible new dataset: Philly parking violations

### ISSUE THREAD

**Issue by phillynerd** [rfordatascience/tidytuesday#147]
Just saw NBC philly do a story on a series of trends for parking tickets.
https://www.nbcphiladelphia.com/news/local/Nearly-6-Million-Philadelphia-Parking-Authority-Tickets-Are-on-the-Rise-Since-2016-565438131.html

So of course I had to check and see if the data were available, and it looks like they are! Thought it could be super interesting, considering how notorious philly PPA is (they're the original focus of Parking Wars, after all).

https://www.opendataphilly.org/dataset/parking-violations

**Comment by jthomasmock** [comment]
Thanks! using this week
