### ISSUE TITLE
Dataset 51 potential issues

### ISSUE THREAD

**Issue by pradeepssundaram** [rfordatascience/tidytuesday#159]
There seems to be some issues with the dog_descriptions data as reading it via readr gave wierd codes for states.

Example ids and state codes

id | contact_state
-- | --
41330726 | 89146
38169117 | 85249
45833989 | 12220
45515547 | 12220

Is this deliberate to help practise cleaning the data / or a text field  having a comma is not quoted?
It looks like the name fields for the records contain commas and may be this is the issue.
Or should we read in the data using a quote parameter.
Thanks,
Pradeep

**Comment by jthomasmock** [comment]
This is an error - will look into it!
