### ISSUE TITLE
2019 data links broken 

### ISSUE THREAD

**Issue by robinsones** [rfordatascience/tidytuesday#162]
The links in the table [here](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019) are broken. For example, the christmas music data link points [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2019/data/2019/2019-12-24) instead of the correct page [here](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-12-24)

**Comment by jthomasmock** [comment]
Ahhh thanks Emily! I thought the relative links would work out ok even with "moving", but will fix these.

**Comment by jthomasmock** [comment]
I believe they are working now @robinsones - do you mind confirming the tables [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2019/README.md) now redirect correctly?

**Comment by robinsones** [comment]
working, thanks!
