### ISSUE TITLE
What's happened in a world last month: world news analysis

### ISSUE THREAD

**Issue by dbs700** [rfordatascience/tidytuesday#18]
Hello! I've started a longtime project on a global news analysis. What if we could collect the most popular news from different countries and continents? What if we would do it every day for a… let's say one month or year?  
https://medium.com/@storozhenko.dmitry/whats-happened-in-a-world-last-month-world-news-analysis-b7e540d45d64

If somebody would like to join, please let me know:)

**Comment by dbs700** [comment]
Data is here 😄 
https://github.com/dbs700/Global-news-dataset

**Comment by tracykteal** [comment]
Thanks @dbs700! I noticed that this dataset is no longer available, so I'm closing out this issue. Thank you though for the idea!
