### ISSUE TITLE
Problem with TBI military data for 03/24/2020

### ISSUE THREAD

**Issue by gklarenberg** [rfordatascience/tidytuesday#186]
It seems the tables from the pdfs were not read in properly. I haven't checked the full cleaning script, but I came across this when I filtered out only the severe data. The first few lines of the dataframe look like this (and I double-checked with the original data to make sure I filtered correctly.

```
service   component severity diagnosed  year
   <chr>     <chr>     <chr>        <dbl> <dbl>
 1 Army      Active    Severe         102  2006
 2 Army      Active    Severe          26  2006
 3 Army      Guard     Severe          11  2006
 4 Navy      Active    Severe          28  2006
 5 Navy      Active    Severe           1  2006
 6 Air Force Active    Severe          24  2006
 7 Air Force Active    Severe           4  2006
 8 Air Force Guard     Severe           2  2006
```
When you go to the pdf for this data (https://dvbic.dcoe.mil/sites/default/files/tbi-numbers/worldwide-totals-2006_jun-21-2018_v1.0_2018-07-26_0.pdf), it shows that "Active" is duplicated and gets the number for "Guard", "Guard" gets the number for "Reserve" and the component "Reserve" falls off. So the above table should be:
```
service   component severity diagnosed  year
   <chr>     <chr>     <chr>        <dbl> <dbl>
 1 Army      Active    Severe         102  2006
 2 Army      Guard    Severe          26  2006
 3 Army      Reserve     Severe          11  2006
 4 Navy      Active    Severe          28  2006
 5 Navy      Reserve    Severe           1  2006
 6 Air Force Active    Severe          24  2006
 7 Air Force Guard    Severe           4  2006
 8 Air Force Reserve     Severe           2  2006
```
I checked a few other severity classes, and for instance "Mild" for 2006 looks okay for Army and Navy, but Air Force has a similar issue as above. "Penetrating" has the same problems as "Severe"

**Comment by jthomasmock** [comment]
Thanks! I'll be working on fixing this tonight.

**Comment by jthomasmock** [comment]
Hi Dr. Klarenburg - thanks for bringing this to my attention, I believe I have corrected it with the latest update to the cleaning script, and re-upload of the raw data.

Thanks for letting me know, and ping me again if you ever see any problems.
