### ISSUE TITLE
Caselaw Access Project - Bulk Download or API

### ISSUE THREAD

**Issue by mjhendrickson** [rfordatascience/tidytuesday#19]
The Caselaw Access Project (CAP) has digitized over 40 million pages of US court decisions. What better way to promote civic engagement than through caselaw?!?

Use the bulk download (currently only IL and AR) without login. Other states with login and user agreement.
Use API for up to 500 cases per user per day.

Service: https://case.law/
Bulk: https://case.law/bulk/
API: https://case.law/api/
Announcement: https://lil.law.harvard.edu/blog/2018/10/29/caselaw-access-project-cap-launches-api-and-bulk-data-service/

**Comment by tracykteal** [comment]
Thanks @mjhendrickson! The Caselaw project has now deactivated parts of this project, including the API, so closing this issue now. Thanks so much though for the idea!
