### ISSUE TITLE
Medium Article Scrape & Analysis

### ISSUE THREAD

**Issue by mjhendrickson** [rfordatascience/tidytuesday#20]
Someone did a web scrape of 1.4 million Medium articles between 8/2017-8/2018, including:
- Title
- Sub-title
- Author
- Publication Date
- Tags
- Read-Time
- Claps-Received
- Story URL
- Author URL

Data: 
https://www.kaggle.com/harrisonjansma/medium-stories

Article - removed as the link is no longer active.
~~https://towardsdatascience.com/i-just-published-a-massive-dataset-of-medium-stories-heres-the-link-to-get-it-889bab324138~~

Github:
https://github.com/harrisonjansma/Analyzing_Medium

**Comment by jthomasmock** [comment]
This week's data! Thanks!
