### ISSUE TITLE
Broadway weekly box office grosses

### ISSUE THREAD

**Issue by tacookson** [rfordatascience/tidytuesday#200]
Broadway theatres have been publishing weekly figures on revenue, seats sold, ticket prices, and percent capacity since 1985, including data for over 1,000 shows. Data comes from [Playbill](https://www.playbill.com/), but is originally from [The Broadway League](https://en.wikipedia.org/wiki/The_Broadway_League)

- [Cleaned Data](https://github.com/tacookson/data/tree/master/broadway-grosses)
- [Scraping and Cleaning Script](https://github.com/tacookson/data/blob/master/broadway-grosses/src/scrape-playbill.R)
- [Draft README](https://github.com/tacookson/data/blob/master/broadway-grosses/ref/tidy-tuesday-readme.md)

**Comment by jthomasmock** [comment]
Fantastic! Used this week, thanks for your submission!

**Comment by ybressler** [comment]
This is a beautiful dataset! Thank you for putting it together!
