### ISSUE TITLE
'...' syntax fails in the 'cleaning data' funtions for Animal Crossing Data Setc

### ISSUE THREAD

**Issue by sdcharle** [rfordatascience/tidytuesday#208]
Whenever I encounter something like this:

 select(-...1) %>% 

it fails. I first of all have had no luck determining what that syntax is (try Googling '...') although it looks like it's just an index thing.

I am using R 4 - maybe this is old deprecated R shorthand? It's driving me crazy not being able to work it out. Thanks for any help.

**Comment by jthomasmock** [comment]
Howdy! Sorry you're running into that issue.

`...1` is a name-repair strategy that [`tidyr::unnest_wider()`](https://tidyr.tidyverse.org/reference/hoist.html) uses when the data being unnested is an unnamed vector. This column should be accessible with `dplyr` or base R, and with a data.frame or tibble. 

It's possible that the column is non-existent in the data output you have?

Note that I am not on R 4.0, but here is a `reprex` with the column name indicated.

``` r
library(dplyr, warn.conflicts = FALSE)

ex_df <- data.frame(...1 = 1:10)

# Works w/ dplyr
select(ex_df, ...1)
#>    ...1
#> 1     1
#> 2     2
#> 3     3
#> 4     4
#> 5     5
#> 6     6
#> 7     7
#> 8     8
#> 9     9
#> 10   10

# Works w/ base R
ex_df[["...1"]]
#>  [1]  1  2  3  4  5  6  7  8  9 10

# Works w/ base R
ex_df$...1
#>  [1]  1  2  3  4  5  6  7  8  9 10
```

<sup>Created on 2020-05-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
