### ISSUE TITLE
Finding Story in Kaggle Machine Learning and Data Science Survey 

### ISSUE THREAD

**Issue by sastoudt** [rfordatascience/tidytuesday#21]
Kaggle is having a competition to find a story in their Machine Learning and Data Science Survey results.
https://www.kaggle.com/kaggle/kaggle-survey-2018/home

Challenge ends December 3rd, but there are weekly prizes as well up until that point.

**Comment by tracykteal** [comment]
Since this competition is no longer ongoing, I'm closing out this issue. Thank you though @sastoudt for the idea!
