### ISSUE TITLE
Covid-19 response of New Zealand government

### ISSUE THREAD

**Issue by thoughtfulbloke** [rfordatascience/tidytuesday#212]
The New Zealand government released all documents relating to their response & decision making to Covid-19 as 325 pdf files

https://covid19.govt.nz/resources/key-documents-and-legislation/proactive-release/

These pdfs have had the text extracted and made available by the New Zealand Herald newspaper 

https://github.com/nzherald/pandemicpapers

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!
