### ISSUE TITLE
African American History Timeline

### ISSUE THREAD

**Issue by jthomasmock** [rfordatascience/tidytuesday#216]
[Dataset source](https://www.blackpast.org/african-american-history-timeline/)

This data is already cleaned and ready to go thanks to the great resources at Blackpast - I just need to write the readme. 

Given my status as a relatively privileged white male, I'd really like to get some additional help and feedback on writing the `readme` for this dataset, especially as it will lead up to the celebration of Juneteenth a little less than two weeks from now. I am OK with drafting it up, but am sensitive to the fact that I do not understand the full significance of this dataset.

**Comment by SamanthaToet** [comment]
Happy to help with this!

**Comment by raviolli77** [comment]
perhaps asking African-American data science community members if they would like to review and potentially contribute to the README?

**Comment by jthomasmock** [comment]
![Abolition of slavery celevration, Washington DC APril 19 1866](https://www.blackpast.org/wp-content/uploads/Abolition_of_slavery_celebration_Washington_DC_April_19_1866_Public_domain_illustration_by_Frederick_Dielman.jpg)

# American Slavery and Juneteenth

The data this week comes from [Wikipedia's US Census](https://en.wikipedia.org/wiki/1790_United_States_Census), [Slave Voyages](https://slavevoyages.org/), and [Black Past](https://www.blackpast.org/african-american-history-timeline/). 

Additional details can be found via [Wikipedia's Article on Slavery in the US](https://en.wikipedia.org/wiki/Slavery_in_the_United_States), [BlackPast.org](https://www.blackpast.org/), and a [Guardian article on Slavery](https://www.theguardian.com/news/2019/aug/15/400-years-since-slavery-timeline).

The goal of this week's TidyTuesday is to share data related to just how widespread slavery was in the history of the United States, highlight the ongoing suppression of Black Lives across hundreds of years and continuing into the present, and celebrate `Juneteenth` (June 19th) which falls on Thursday of this year.

![Juneteenth Inscription](https://s.hdnux.com/photos/74/03/45/15743330/3/rawImage.jpg)

[Texas Historical Commission Juneteenth Inscription](https://www.thc.texas.gov/public/upload/Juneteenth%20%2814GV08%29%20inscription.pdf)

> COMMEMORATED ANNUALLY ON JUNE 19TH, JUNETEENTH IS THE OLDEST KNOWN CELEBRATION OF THE END OF SLAVERY IN THE U.S. THE EMANCIPATION PROCLAMATION, ISSUED BY PRESIDENT ABRAHAM LINCOLN ON SEP. 22, 1862, ANNOUNCED, “THAT ON THE 1ST DAY OF JANUARY, A.D. 1863, ALL PERSONS HELD AS SLAVES WITHIN ANY STATE…IN REBELLION AGAINST THE U.S. SHALL BE THEN, THENCEFORWARD AND FOREVER FREE.” HOWEVER, IT WOULD TAKE THE CIVIL WAR AND PASSAGE OF THE 13TH AMENDMENT TO THE CONSTITUTION TO END THE BRUTAL INSTITUTION OF AFRICAN AMERICAN SLAVERY.  AFTER THE CIVIL WAR ENDED IN APRIL 1865 MOST SLAVES IN TEXAS WERE STILL UNAWARE OF THEIR FREEDOM. THIS BEGAN TO CHANGE WHEN UNION TROOPS ARRIVED IN GALVESTON. MAJ. GEN. GORDON GRANGER, COMMANDING OFFICER, DISTRICT OF TEXAS, FROM HIS HEADQUARTERS IN THE OSTERMAN BUILDING (STRAND AND 22ND ST.), READ ‘GENERAL ORDER NO. 3’ ON JUNE 19, 1865. THE ORDER STATED “THE PEOPLE OF TEXAS ARE INFORMED THAT, IN ACCORDANCE WITH A PROCLAMATION FROM THE EXECUTIVE OF THE UNITED STATES, ALL SLAVES ARE FREE. THIS INVOLVES AN ABSOLUTE EQUALITY OF PERSONAL RIGHTS AND RIGHTS OF PROPERTY BETWEEN FORMER MASTERS AND SLAVES.” WITH THIS NOTICE, RECONSTRUCTION ERA TEXAS BEGAN.  FREED AFRICAN AMERICANS OBSERVED “EMANCIPATION DAY,” AS IT WAS FIRST KNOWN, AS EARLY AS 1866 IN GALVESTON. AS COMMUNITY GATHERINGS GREW ACROSS TEXAS, CELEBRATIONS INCLUDED PARADES, PRAYER, SINGING, AND READINGS OF THE PROCLAMATION. IN THE MID-20TH CENTURY, COMMUNITY CELEBRATIONS GAVE WAY TO MORE PRIVATE COMMEMORATIONS. A RE-EMERGENCE OF PUBLIC OBSERVANCE HELPED JUNETEENTH BECOME A STATE HOLIDAY IN 1979. INITIALLY OBSERVED IN TEXAS, THIS LANDMARK EVENT’S LEGACY IS EVIDENT TODAY BY WORLDWIDE COMMEMORATIONS THAT CELEBRATE FREEDOM AND THE TRIUMPH OF THE HUMAN SPIRIT.

With these datasets we can piece together a grim picture of the kidnapping, transport, and enslavement of MILLIONS of African people into the Americas and throughout the world across hundreds of years. Additional focus is given across the data for those enslaved into British America or the United States of America itself from 1600-1865. The Black Past dataset adds additional details around the slow granting of various rights to African-Americans, post-slavery brutality, violence and racism, and then celebrations of achievements across many different categories. The census data highlights the total slave populations across the United States during the slavery era. This included children born into slavery.

> In 1820 a child in the Upper South had a 30% chance of being sold south by 1860.

The Guardian put together a [detailed article](https://www.theguardian.com/news/2019/aug/15/400-years-since-slavery-timeline) with many graphs highlighting the widespread practice of slavery and subsequent post-slavery racism against Black people in the United States across 400 years (1619 to 2019).

**Comment by jthomasmock** [comment]
Used for this week.
