### ISSUE TITLE
November 20th Transgender Day of Remembrance data

### ISSUE THREAD

**Issue by hturner** [rfordatascience/tidytuesday#22]
I know it is short notice, but tomorrow is the Transgender Day of Remembrance. Forwards, Rainbow R and Cardiff RUG held a datathon at the weekend to work on a dataset of reports of killings and suicides of transgender people, who will be memorialized on TDoR. More about the datathon can be found here: https://github.com/rlgbtq/TDoR2018. The data is now available as an R package: https://github.com/CaRdiffR/tdor. Although a difficult subject, it would be great if R folk could explore this data for Tidy Tuesday and raise awareness of TDoR.

**Comment by hturner** [comment]
Some discussion of potential visualisations/exploration in issues 7 and 8 here https://github.com/rlgbtq/TDoR2018/issues

**Comment by jthomasmock** [comment]
Hi Heather, I'll add it to this week's data along with the already uploaded dataset - thanks for passing along!

**Comment by hturner** [comment]
Thanks for adding it in! I'll advertise it on the Forwards Twitter,
