### ISSUE TITLE
U.S. Colleges’ Plans for Reopening in the Fall

### ISSUE THREAD

**Issue by SarahGillespie** [rfordatascience/tidytuesday#221]
**School plans:**

The school plans data can be downloaded from The Chronicle of Higher Education’s frequently updated list titled “Here’s a List of Colleges’ Plans for Reopening in the Fall” (https://www.chronicle.com/article/Here-s-a-List-of-Colleges-/248626?utm_source=at&utm_medium=en&utm_source=Iterable&utm_medium=email&utm_campaign=campaign_1209367&cid=at&source=ams&sourceId=378492) tracking nearly a thousand school’s fall 2020 plans. The list did not specify how each school was selected. There is an option to submit untracked institutions to the list, which means the large sample size is not necessarily randomly selected from all the higher education institutions in the United States. This data set is updated about once per day as of July 17th.

**Other relevant data sets:**

Harvard’s Opportunity Insights Baseline Cross-Sectional Estimates of Child and Parent Income Distributions by College (https://opportunityinsights.org/data/?geographic_level=100&topic=0&paper_id=0#resource-listing). 

United States Department of Education’s most recent institution-level data (https://collegescorecard.ed.gov/data/). I had to bring the Department of Education data into Excel and removed unnecessary columns because the downloaded csv was too large for my Rstudio desktop version to open.

Kaggle spreadsheet created by Omer Shacham (https://www.kaggle.com/omer2040/usa-states-to-region) to categorize each school’s state into regions and divisions of the United States.

World Population Review 2016 Election Results By State (https://worldpopulationreview.com/states/2016-election-results-by-state/) is a spreadsheet for each state’s presidential election results broken down by state population and percentage for each candidate.

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!
