### ISSUE TITLE
Astronaut Database (week 29) missing field. 

### ISSUE THREAD

**Issue by delabj** [rfordatascience/tidytuesday#232]
I think I may have figured out what the missing field is. 

In the data dictionary field21 is listed with a description of  "?", and this sparked my interest. I did a little digging, and found that it was very correlated with the EVA columns. This made me think it might be instances of EVA by mission. 

I ended up finding the paper here: https://www.sciencedirect.com/science/article/pii/S2214552420300444 and since I had access through my school, I downloaded it and found the following dataset description:

> The following information was included: 1) identification (official and Romanised name, national database ID number, and retirement status); 2) demographics (nationality, sex, year of birth, year of selection, and military background); 3) career statistics (total time spent in space, number of flights, and extra-vehicular activity (EVA) hours); and 4) data on each mission involving the traveler (the name, year, and duration of each mission; ascent/orbit/descent vehicle; and **instances of** and total EVA time per mission).

Emphasis is mine. 

I'm fairly certain that this is that EVA instances of per mission field since there doesn't appear to be another field.

**Comment by jthomasmock** [comment]
Added to the data dictionary - thank you!

I didn't have access to the paper :(
