### ISSUE TITLE
Plants in Danger (IUCN Red List)

### ISSUE THREAD

**Issue by Z3tt** [rfordatascience/tidytuesday#236]
Hi Thomas, 
Florent gratefully sent the data from his fantastic viz about extinction of plants worldwide to me.

 I have prepared a full challenge incl. links, cleaning script, and dictionary. You can find the raw and processed data as well as the script and the readme on my [#TidyTuesday GitHub](https://github.com/Z3tt/TidyTuesday/tree/master/data/raw_plants).

Cheers,
Cédric

**Comment by jthomasmock** [comment]
Thanks Cedric!
