### ISSUE TITLE
Cost of Beer at MLB Stadiums

### ISSUE THREAD

**Issue by mjhendrickson** [rfordatascience/tidytuesday#24]
From data.world and originally posed as a Tableau Makeover Monday: the cost of beer at MLB stadiums. The original visualization is a good exercise in recreating a comparative plot. This would also be a good use case to explore creating a Shiny app.

Article: https://data.world/makeovermonday/2018w43-what-will-a-beer-cost-you-at-every-major-league-ba
Data - requires login via link above. You can create an account and login with GitHub credentials.

**Comment by tracykteal** [comment]
This is a great idea! Since the dataset is now older though, I'm going to go ahead and close out this issue.
