### ISSUE TITLE
Taylor Swift

### ISSUE THREAD

**Issue by jthomasmock** [rfordatascience/tidytuesday#245]
https://rpubs.com/RosieB/taylorswiftlyricanalysis

**Comment by sastoudt** [comment]
Beyoncé companion data [here](https://gist.github.com/sastoudt/cdc16a5a19cf9ae34db0231782231f27).

**Comment by RosieBaillie** [comment]
CSV of Taylor Swift lyrics. 
[TSwiftLyrics.zip](https://github.com/rfordatascience/tidytuesday/files/5208782/TSwiftLyrics.zip)
