### ISSUE TITLE
Analyze Public Opinion Survey on LA2028 Olympics

### ISSUE THREAD

**Issue by NOlympicsLA** [rfordatascience/tidytuesday#25]
NoOlympics LA conducted a large survey (>1000 respondents) on public opinion regarding the Olympics. This provides real survey responses for TidyTuesday participants to analyze and visualize. 

Github link with more info, context and basic analyses.
https://github.com/NOlympicsLA/Olympics-Public-Survey

**Comment by tracykteal** [comment]
Thanks so much for bringing this idea here @NOlympicsLA! Since the data is from awhile ago now, I'm going to go ahead and close out this issue. We'd welcome new data though, if there's something you'd like to share.
