### ISSUE TITLE
Apple COVID-19 Data

### ISSUE THREAD

**Issue by jhelvy** [rfordatascience/tidytuesday#252]
Data on travel by mode  generated by counting the number of requests made to Apple Maps for directions in select locations. An interesting view into how people are traveling before & after the COVID pandemic.

https://www.apple.com/covid19/mobility

**Comment by kelseygonzalez** [comment]
Related, here's a r package that has this apple data + other covid-19 datasets:
https://kjhealy.github.io/covdata/

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!
