### ISSUE TITLE
Friends dataset

### ISSUE THREAD

**Issue by EmilHvitfeldt** [rfordatascience/tidytuesday#254]
I find that this data could be fun both for text analysis but also for graph analysis :)

# Friends

The data this week comes from the [`friends` R package](https://github.com/EmilHvitfeldt/friends) for the Friends transcripts and additional information.

The `friends` package can be installed from CRAN with `install.packages("friends")`. 

This [ceros interactive article](https://www.ceros.com/originals/friends-scripts-25th-anniversary-catchphrase-scenes-quotes/) looks at which characters appear together. 

### Data Dictionary

# `friends` data

|variable    |class     |description |
|:-----------|:---------|:-----------|
|text      |character    | Dialogue as text |
|speaker     |character    | Name of the speaker |
|season       |double | Season Number |
|episode |double    | Episode Number |
|scene |double    | Scene Number |
|utterance    |double | Utterance Number|

# `friends_emotions` data

|variable    |class     |description |
|:-----------|:---------|:-----------|
|season       |integer | Season Number |
|episode |integer    | Episode Number |
|scene |integer    | Scene Number |
|utterance    |integer | Utterance Number|
| emotion | character | One of 7 emotions |

# `friends_entities` data

|variable    |class     |description |
|:-----------|:---------|:-----------|
|season       |integer | Season Number |
|episode |integer    | Episode Number |
|scene |integer    | Scene Number |
|utterance    |integer | Utterance Number|
| entities | list | Character entities |

# `friends_info` data

|variable    |class     |description |
|:-----------|:---------|:-----------|
|season       |integer | Season Number |
|episode |integer    | Episode Number |
|title |character    | Title |
|directed_by    |character | Name of director(s)|
| written_by | character | Name of writer(s) |
| air_date | date | Original Airing date in USA |
| us_views_millions | double | Viewers in USA in millions |
| imdb_rating | double | IMDB Rating (10 is best) |

### Cleaning Script

No cleaning this week!

**Comment by NeilEcosse** [comment]
https://github.com/NeilEcosse/text_analysis_friends

**Comment by prajwalsouza** [comment]
Thank you for this clean data. After spending hours and days cleaning other datasets. This appears to be a gold mine. :)

**Comment by NeilEcosse** [comment]
Ah thanks! Yes, I spent a while on it for a college project, heh-heh!NeilOn 2 Jan 2024, at 10:43, Prajwal DSouza ***@***.***> wrote:﻿
Thank you for this clean data. After spending hours and days cleaning other datasets. This appears to be a gold mine. :)
