### ISSUE TITLE
Link for tractor dataset, week 36

### ISSUE THREAD

**Issue by charlie-gallagher** [rfordatascience/tidytuesday#256]
In the README for week 36, the tractor dataset's link is written as `https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/cereal_yields_vs_tractor_inputs_in_agriculture.csv`. The end should read `2020/2020-09-01/cereal_yields_vs_tractor_inputs_in_agriculture.csv` instead.

**Comment by jonthegeek** [comment]
This appears to have been fixed at some point in the past. Thanks for the report!
