### ISSUE TITLE
Beyance Album missing from 09-29-2020 Dataset 

### ISSUE THREAD

**Issue by hunterkempf** [rfordatascience/tidytuesday#263]
for the Taylor Swift and Beyance data the [sales.csv](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-09-29/sales.csv) and charts.csv are missing Beyance's Lemonade album (It seems like an error in parsing the wikipedia page) https://en.wikipedia.org/wiki/Beyonc%C3%A9_discography#Studio_albums

**Comment by jthomasmock** [comment]
Thanks! Updated
