### ISSUE TITLE
Tunnel length and percentage in Transit Cost Project

### ISSUE THREAD

**Issue by gkaramanis** [rfordatascience/tidytuesday#293]
The columns `tunnel` and `tunnel_per` seem to be about the length and percentage of the line that is tunneled, not completed 😊

![2CBDBCE5-6883-4F95-A27D-4D2719B1ACBF](https://user-images.githubusercontent.com/3393168/103935344-b9a2e680-5126-11eb-9d71-aa14c417bbaf.jpeg)

**Comment by jonthegeek** [comment]
I don't think that's a significant enough difference to bother with (the tunnelling is completed, or tunneled, the wording is close enough to the same).
