### ISSUE TITLE
Data from the "COVID-19 Disorder Tracker"

### ISSUE THREAD

**Issue by jmcastagnetto** [rfordatascience/tidytuesday#303]
From: https://acleddata.com/analysis/covid-19-disorder-tracker/

> The COVID-19 Disorder Tracker (CDT) provides special coverage of the pandemic’s impact on political violence and protest trends around the world, monitoring changes in demonstration activity, state repression, mob attacks, overall rates of armed conflict, and more.

From: https://acleddata.com/curated-data-files/

> ACLED is an event-based data project designed for disaggregated conflict analysis and crisis mapping. Data are updated weekly and can be downloaded using the Data Export Tool. For those interested in accessing all ACLED data for a particular region or topic, regional and curated data files can be downloaded ...

**Important**: Getting the files requires registration, and according to https://twitter.com/ACLEDINFO/status/1354468998713397250 their terms of use allow for non-commercial use with attribution.

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!

**Comment by Felipepereyra** [comment]
Please i want to unsubscribe, I've done it multiple times

**Comment by jonthegeek** [comment]
@Felipepereyra Click through to GitHub, and click "Unsubscribe" on the issue, and/or go to the main repo at https://github.com/rfordatascience/tidytuesday and click "Unwatch". We cannot change this setting for you, unfortunately.
