### ISSUE TITLE
Data submission: COVID-19 Vulnerability Index

### ISSUE THREAD

**Issue by MikeJohnPage** [rfordatascience/tidytuesday#307]
**Dataset**: [British Red Cross COVID-19 Vulnerability Index](https://raw.githubusercontent.com/britishredcrosssociety/covid-19-vulnerability/master/output/vulnerability-MSOA-England.csv)

**Article**: [README from the open source repository](https://github.com/britishredcrosssociety/covid-19-vulnerability/blob/master/README.md)

**Additional info**: this data set contains information on vulnerabilities to COVID-19 in English Middle Super Output Areas (data is also available for the other devolved nations at different geographic levels [here](https://github.com/britishredcrosssociety/covid-19-vulnerability/tree/master/output)).

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!
