### ISSUE TITLE
Superbowl adds

### ISSUE THREAD

**Issue by jthomasmock** [rfordatascience/tidytuesday#310]
https://twitter.com/datadhrumil/status/1357368234853486595?s=21

**Comment by kelseygonzalez** [comment]
Came here to submit the same thing, @jthomasmock ! You're on top of it.

Here's an actual link to the data source: https://github.com/fivethirtyeight/superbowl-ads
and a description from Data Is Plural Mailing list (where I came across it):

> **Super Bowl ads.** Journalists at FiveThirtyEight watched 233 Super Bowl ads run by 10 frequently-advertising brands between 2000 and 2020, drawing from superbowl-ads.com’s video archive. Then they categorized each ad according to seven specific questions, which included “Was it trying to be funny?” and “Did it include animals?”
