### ISSUE TITLE
Status of COVID-19 cases in Ontario, Canada

### ISSUE THREAD

**Issue by zhs-1997** [rfordatascience/tidytuesday#318]
The Daily change in cases by PHU(Public Health Unit) dataset: (from the government of Ontario):
[daily_change_in_cases_by_phu.csv.zip](https://github.com/rfordatascience/tidytuesday/files/5990918/daily_change_in_cases_by_phu.csv.zip)

See https://open.canada.ca/data/en/dataset/f4f86e54-872d-43f8-8a86-3892fd3cb5e6 for more info.
The covid cases are going down now. But based on the historical data, we should be careful about a third peak in the future if we reopen everything too soon. 

Stay safe.

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!
