### ISSUE TITLE
Survey data on Covid-19 symptoms

### ISSUE THREAD

**Issue by zhs-1997** [rfordatascience/tidytuesday#323]
[dataverse_files (1).zip](https://github.com/rfordatascience/tidytuesday/files/6080324/dataverse_files.1.zip)
Some interesting survey data provided by the University of Toronto: https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/YM8BCJ

As seen in the codebook, all survey questions have been modified for data analysis purposes. It is easy to do the coding for the qualitative data.

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!
