### ISSUE TITLE
COVID-19 impact on residents' travel decision

### ISSUE THREAD

**Issue by zhs-1997** [rfordatascience/tidytuesday#325]
[travel.zip](https://github.com/rfordatascience/tidytuesday/files/6094660/travel.zip)
COVID-19 Disruption on Travel Patterns data for the Puget Sound Region in Washington State.

Related webpage: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FN8RZK
This is survey data from the Harvard dataverse. Should be useful for predicting future travel decisions during the pandemic.

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!
