### ISSUE TITLE
Vaccination data

### ISSUE THREAD

**Issue by jlkuee** [rfordatascience/tidytuesday#336]
A data about COVID-19 World Vaccination Progress. 
The original data is from https://github.com/owid/covid-19-data
The merged data is here: https://www.kaggle.com/gpreda/covid-world-vaccination-progress

**Comment by samcarlen** [comment]
Where does this data come from? Unless I am missing something, the article to which you linked does not describe what the dataset represents/where the data came from.

**Comment by jlkuee** [comment]
> Where does this data come from? Unless I am missing something, the article to which you linked does not describe what the dataset represents/where the data came from.

I didn't find the original source neither, it seems like it is a sample dataset for coding. I'm not sure where it is come from. 
However, when I tried to seek the source, I found another interesting dataset about Covid-19 Vaccination, which is from Our World in Data. I change this issue to the new data.

**Comment by jonthegeek** [comment]
Thank you for the submission! We avoided COVID-related datasets so people could use TidyTuesday to escape from that particular reality. Too many people have lost loved ones to this disease, so we wanted to avoid causing further pain. Thanks again, and we hope you have continued to enjoy TidyTuesday!
