### ISSUE TITLE
Great British Bake Off/Baking Show

### ISSUE THREAD

**Issue by jonthegeek** [rfordatascience/tidytuesday#343]
https://github.com/apreshill/bakeoff
I could have sworn we'd already done this, but I can't find it. I imagine it'd make for some great visualizations!

**Comment by kelseygonzalez** [comment]
Seconded! I immediately thought of this when I saw @apreshill 's new package.

**Comment by apreshill** [comment]
Fresh on CRAN @jthomasmock 

https://cran.r-project.org/web/packages/bakeoff/index.html

**Comment by jonthegeek** [comment]
https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-10-25
