### ISSUE TITLE
missing `stocked.csv` in static/tt_data_type.csv

### ISSUE THREAD

**Issue by ha0ye** [rfordatascience/tidytuesday#347]
Using {{tidytuesdayR}} to get the data fro 2021-06-08, I noticed that only the `fishing.csv` table was downloaded. Tracing this issue back, I see that `static/tt_data_type.csv` only has a single line for this week's data - https://github.com/rfordatascience/tidytuesday/blob/master/static/tt_data_type.csv#L2

and is missing `stocked.csv`, which otherwise exists in the corresponding data folder - https://github.com/rfordatascience/tidytuesday/tree/master/data/2021/2021-06-08

**Comment by jthomasmock** [comment]
I have corrected this with the latest push. Thanks!
