### ISSUE TITLE
Tidy Tuesday hexagon icon

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [rfordatascience/tidytuesday#359]
This repository has no R hexagon icon to be used for references and cool R stickers, so here is my contribution to help with that. Since many plots have white background there is a shade element so the logo stands out if and when it is used on white or light backgrounds. 
I added my Twitter name as to give reference to my work and tried to not steal too much attention from the logo's message. Hope this gets added to the official use and would make me very happy.

Thanks for posting if/when you do. My Name is Zane Dax. 😄 🏳️‍🌈 

![tidyTuesday hexagon](https://user-images.githubusercontent.com/55933131/126205497-e2344391-144f-4d65-98ee-10d57aeceb80.png)

**Comment by abichat** [comment]
There is a logo for the TidyTuesday project, available [here](https://github.com/rfordatascience/tidytuesday/blob/master/static/tt_hex.png).

**Comment by PythonCoderUnicorn** [comment]
> There is a logo for the TidyTuesday project, available [here](https://github.com/rfordatascience/tidytuesday/blob/master/static/tt_hex.png).

Oh okay. I guess I wasted my time. Never seen anyone use it.
