### ISSUE TITLE
Billboard Charts + Spotify Track Features

### ISSUE THREAD

**Issue by wurli** [rfordatascience/tidytuesday#364]
Data for both can be found [here](https://data.world/kcmillersean/billboard-hot-100-1958-2017). The Billboard data goes from 1958 to 2021.

**Comment by preshitambade** [comment]
please unsubscribe my email :preshitambade@gmail.com from the listserv. Thank you.

**Comment by jthomasmock** [comment]
Used for week 38 2021, thanks!
