### ISSUE TITLE
Repository with many data sets

### ISSUE THREAD

**Issue by liberrenaud** [rfordatascience/tidytuesday#38]
https://www.figure-eight.com/data-for-everyone/

- Image descriptions
- Judge emotions about nuclear energy from Twitter
- Decide whether two English sentences are related
- Similarity judgment of word combinations
- Sentiment Analysis – Global Warming/Climate Change
- Judge Emotion About Brands & Products
- Colors in 9 Languages
- Claritin Twitter
- Sentence plausibility
- Academy Awards demographics
- Agreement between long and short sentences
- Company categorizations (with URLs)

Thanks for setting up Tidy Tuesday in the first place!!

**Comment by tracykteal** [comment]
Thanks @liberrenaud! Since this datasets page is no longer maintained, I'm going to go ahead and close out this issue. Thanks so much for the idea though!
