### ISSUE TITLE
Board Game Geek

### ISSUE THREAD

**Issue by dbaranger** [rfordatascience/tidytuesday#382]
Data from https://boardgamegeek.com/ where users review board games. Data is here: https://www.kaggle.com/andrewmvd/board-games
Includes game rank and details on each game. Lots of rich data!

**Comment by gkaramanis** [comment]
+1 for this!

Updated dataset: https://www.kaggle.com/jvanelteren/boardgamegeek-reviews

Analysis:
https://jvanelteren.github.io/blog/2022/01/19/boardgames.html
