### ISSUE TITLE
Afrimapr

### ISSUE THREAD

**Issue by jonthegeek** [rfordatascience/tidytuesday#390]
https://github.com/afrimapr/afrilearndata
Various Africa datasets. They're also focusing on the 30 day map challenge and discussing on r4ds.

**Comment by andysouth** [comment]
This would be great - let us know if we can do anything else to assist.

We also have > 100 k health facility points for Africa if people wanted more data to get their teeth into 
https://github.com/afrimapr/afrihealthsites

**Comment by jthomasmock** [comment]
Used for previous week, thanks!
