### ISSUE TITLE
Data suggestion : Doctor Who episodes

### ISSUE THREAD

**Issue by KittJonathan** [rfordatascience/tidytuesday#392]
Hi there ! 
I put the list of Doctor Who episodes with air dates, ratings, viewers, writers, ... from the wiki page (https://en.wikipedia.org/wiki/List_of_Doctor_Who_episodes_(2005%E2%80%93present) in a package which is now on CRAN (https://cran.r-project.org/web/packages/datardis/index.html). Would that be a dataset for a #TidyTuesday challenge ?

**Comment by KittJonathan** [comment]
I just uploaded a [blog post](https://randomics.netlify.app/posts/2021-11-16-datardis/) about the package with an example

**Comment by jthomasmock** [comment]
Thanks! Used this week
