### ISSUE TITLE
Week 49, 2021 - cricket data - incorrect column names?

### ISSUE THREAD

**Issue by jacquietran** [rfordatascience/tidytuesday#396]
Hi there @jthomasmock!

In the cricket data set for TT week 49 of 2021, there are two column names that are ambiguous / incorrect:

```r
matches <- readr::read_csv(
     'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-11-30/matches.csv')
View(matches)
```

![image](https://user-images.githubusercontent.com/10459045/144158801-c5f464d3-0f19-4684-bda9-a0b1b3f23172.png)

## Potential issue

- The column `wickets_team2` actually corresponds to the team listed in the column `team1` - for example, the game stats for the highlighted record can be found [here](https://www.espncricinfo.com/series/england-tour-of-south-africa-1995-96-61699/south-africa-vs-england-1st-odi-64511/full-scorecard) showing that South Africa (`team1`) lost 8 wickets that day.
- The column `wickets_team` corresponds to the team listed in column `team2`.

Is this intentional (i.e., a "messy" data challenge for people to work with)? Even if so, I wonder if it's best to correct these column names as I'm not sure many people would have thought to check? It could be an easy assumption to make that `wickets_team` is meant to be `wickets_team1` (but that's not the right correction).

## Proposed solution

- Change the name of the column `wickets_team2` to `wickets_team1`
- Change the name of the column `wickets_team` to `wickets_team2`

**Comment by jthomasmock** [comment]
Howdy!

Data was just imported as is from @hassannasir - perhaps they can weigh in. Otherwise, I can change that (or if you want to do a PR, I can give you credit for the contribution).

**Comment by hassannasir** [comment]
Hi Tom,

I scrapped data from ESPN Cricinfo website and wrangled it in it's current
form.

I can share scrapping script if needed.

Regards,
Hassan

**Comment by hassannasir** [comment]
@jacquietran <https://github.com/jacquietran>*'s proposal seems correct. *

*I have been traveling so I couldn't see it properly as I have been away
from my computer. I can correct soon. *
