### ISSUE TITLE
Chocolate bar reviews

### ISSUE THREAD

**Issue by gkaramanis** [rfordatascience/tidytuesday#408]
http://flavorsofcacao.com/chocolate_database.html

From Data Is Plural:

> Chocolate bar reviews. The Manhattan Chocolate Society’s Brady Brelinski has reviewed 2,500+ bars of craft chocolate since 2006, and compiles his findings into a copy-paste-able table that lists each bar’s manufacturer, bean origin, percent cocoa, ingredients, review notes, and numerical rating. Related: Craft chocolate makers in the US and Canada, also compiled by Brelinski. [h/t Andrew Maranhão]

**Comment by kelseygonzalez** [comment]
I came here to post the same one, @gkaramanis ! So, +1 !

source: https://www.data-is-plural.com/archive/2022-01-12-edition/
