### ISSUE TITLE
R Package  Presidential Election Polls from 1980 to 2016

### ISSUE THREAD

**Issue by mschmidty** [rfordatascience/tidytuesday#41]
[Data](https://github.com/elliottmorris/politicaldata/tree/master/data) can be found [here](https://github.com/elliottmorris/politicaldata) and is part of a package.   I discovered the data here - https://twitter.com/gelliottmorris/status/1089612612474732544.

**Comment by tracykteal** [comment]
Thanks @mschmidty! I'm going through past issues. Since this is now not a current dataset, I'm going to go ahead and close this out, but thank you so much for the idea!
