### ISSUE TITLE
Data description isn't clear (2022-02-01)

### ISSUE THREAD

**Issue by PursuitOfDataScience** [rfordatascience/tidytuesday#416]
`Dog Breed` dataset from this [link](https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-02-01) `breed_traits.csv` should give some explanation on 1-5 scaling. Is 5 better than 1 or worse than 1. Otherwise, data analysis would be a bit nebulous. Thanks!

**Comment by kkakey** [comment]
The corresponding values can be found in `trait_description.csv` [link](https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-02-01#trait_descriptioncsv) - I hope that's helpful!
