### ISSUE TITLE
Data: Historical weather forecasts and observed temperatures

### ISSUE THREAD

**Issue by speegled** [rfordatascience/tidytuesday#443]
US National Weather Service data from 160 cities as distributed by the University of Illinois listserve since February 1, 2021, organized into a single data frame. [Repo is here](https://github.com/speegled/weather_forecasts). 

Weather data `data/email_data_expanded.csv` includes:

1. date
2. city
3. state
4. high or low
5. how many hours in advance is the forecast
6. observed temp
7. forecast temp
8. observed precipitation
9. forecast outlook

In addition, there is city level data `data/cities.csv` which includes:

1. city
2. state
3. longitude
4. latitude
5. koppen classification
6. elevation
7. distance to coast
8. mean wind speed
10. elevation change 1
11. elevation change 2
12. mean annual precipitation

Example: 

```
wf <- read.csv("https://raw.githubusercontent.com/speegled/weather_forecasts/main/data/email_data_expanded.csv")
cities <- read.csv("https://raw.githubusercontent.com/speegled/weather_forecasts/main/data/cities.csv")

wf <- left_join(wf, cities)

wf %>% 
  filter(high_or_low == "high", forecast_hours_before == 48, possible_error == "none") %>% 
  mutate(error = observed_temp - forecast_temp) %>% 
  ggplot(aes(x = koppen, y = error)) + 
  geom_boxplot()
```

**Comment by jonthegeek** [comment]
This is great! I'm putting together a pull request to use it next week!
