### ISSUE TITLE
tuesdata <- tidytuesdayR::tt_load('2022-08-02') produces an error

### ISSUE THREAD

**Issue by jmouchnino** [rfordatascience/tidytuesday#449]
```
tuesdata <- tidytuesdayR::tt_load('2022-08-02') # or tuesdata <- tidytuesdayR::tt_load(2022, week = 31)
```
```
--- Compiling #TidyTuesday Information for 2022-08-02 ----
--- There is 1 file available ---
--- Starting Download ---

	Downloading file 1 of 1: `frogs.csv`
Error in parse_url(url) : length(url) == 1 is not TRUE
```

But reading in the data manually works
`frog <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-08-02/frog.csv')`

**Comment by B0ydT** [comment]
Before seeing this I googled the error message and found [this similar one](https://github.com/thebioengineer/tidytuesdayR/issues/88).

I think the issue is that the function expects to find frogs.csv but the actual file is called frog.csv.

**Comment by jmouchnino** [comment]
Now reading directly the file does not wark anymore
```
> frog <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-08-02/frog.csv')
Error in open.connection(4L, "rb") : HTTP error 404.
```
