### ISSUE TITLE
Yarn data from ravelry.com

### ISSUE THREAD

**Issue by awalsh17** [rfordatascience/tidytuesday#463]
A dataset of yarns from the knitting and crocheting website, [ravelry.com](https://www.ravelry.com/yarns/)
This yarn data is a table of 100,000 yarns collected via the ravelry API. 

I emailed Ravelry to confirm that this data could be used for education/entertainment purposes. The only data that should not be used would be notes copyrighted by a brand (not in this data).

The data includes information on the yarn name, weight, machine washable, rating_average, rating_count, texture, yardage, company name, etc.

The yarn data is a csv with 100000 rows and 24 variables.

If you like this idea, I put the data and a data dictionary here: https://github.com/awalsh17/ravelry_yarns 

Other yarn attributes (animal or synthetic fiber, fiber type, needle size) could be shared, but the primary data might be sufficiently interesting.

This is my first dataset suggestion - I don't have an article on the data, but I suppose I could create one?

**Comment by jthomasmock** [comment]
Thanks!
