### ISSUE TITLE
Stranger Things Dialogue Dataset

### ISSUE THREAD

**Issue by filmicaesthetic** [rfordatascience/tidytuesday#464]
The dialogue data was extracted from PDFs on [8flix.com](https://8flix.com/collections/transcripts/stranger-things-2/) and additional data containing episode details was scraped from [Wikipedia](https://en.wikipedia.org/wiki/List_of_Stranger_Things_episodes). 

Cleaning scripts & cleaned dataset: [filmicaesthetic/stringr-things](https://github.com/filmicaesthetic/stringr-things)

Credit: [Dan Fellowes](https://twitter.com/FilmicAesthetic) & [Jonathan Kitt](https://twitter.com/KittJonathan)

**Comment by jthomasmock** [comment]
Used this week - thanks!
