### ISSUE TITLE
Radio Stations in the USA

### ISSUE THREAD

**Issue by frankiethull** [rfordatascience/tidytuesday#466]
Created a repo for this one. Cleaned up & aggregated the dataset via wikipedia. 

It's a very interesting one I hope to see shared! Radio stations across the USA tell an interesting story! The format column is a tough stringr problem with overlapping genre types (classic rock, classic hits, classic country, alternative rock, religious, catholics, etc). 

repo:
https://github.com/frankiethull/fm_stations/tree/main

dataset: 
https://github.com/frankiethull/fm_stations/blob/main/state_stations.csv

cleaning script: 
https://github.com/frankiethull/fm_stations/blob/main/cleaning_script.R

data source: 
Grabbing the underlying data from state-by-state links via this source: https://en.wikipedia.org/wiki/Lists_of_radio_stations_in_the_United_States

**Comment by jthomasmock** [comment]
Thanks!
