### ISSUE TITLE
English Premier League 2021-22 Match Data

### ISSUE THREAD

**Issue by evangower** [rfordatascience/tidytuesday#469]
You can explore match day statistics of every game and every team during the 2021-22 season of the English Premier League [Data](https://www.kaggle.com/datasets/evangower/premier-league-match-data/settings)

Data includes teams playing, date, referee, and stats for home and away side such as fouls, shots, cards, and more! Also included is a dataset of the weekly rankings for the season.

The data was collected from the official website of the Premier League. I then cleaned the data using google sheets

Project I did with the data [Who wins the EPL if games end at half time?](https://www.kaggle.com/code/evangower/who-wins-the-epl-if-games-end-at-half-time/notebook?scriptVersionId=109590220) and a article from the Athletic about fouls conceded per yellow card [article](https://theathletic.com/3459766/2022/07/29/liverpool-manchester-city-premier-league-fouls-yellow-card/?source=googlesearch?redirected=1#)

**Comment by evangower** [comment]
Another project I did with the dataset
[2021-22 English Premier League: Extensive EDA](https://app.datacamp.com/workspace/w/ea619459-de92-437c-9177-561da039edc8)

**Comment by tracykteal** [comment]
Thanks so much @evangower! We used this for the April 5th dataset! 
https://github.com/rfordatascience/tidytuesday/pull/539
