### ISSUE TITLE
Rstudio conf R learning survey data

### ISSUE THREAD

**Issue by oscarbaruffa** [rfordatascience/tidytuesday#47]
Very interesting dataset for the R community. Survey conducted prior to Rstudio conf 2019 abotu R users and how they are learning R. 

https://github.com/rstudio/learning-r-survey

**Comment by jthomasmock** [comment]
Good call!

**Comment by tracykteal** [comment]
I'm going through past issues. Since this is now not a current dataset, I'm going to go ahead and close this out, but thank you so much for the idea @oscarbaruffa!
