### ISSUE TITLE
FIFA World Cup Matches

### ISSUE THREAD

**Issue by evangower** [rfordatascience/tidytuesday#472]
As we count down to the start of the FIFA World Cup in Qatar on November 20, this new [dataset](https://www.kaggle.com/datasets/evangower/fifa-world-cup) covers every single World Cup match played in its history from Uruguay in 1930 to Russia in 2018.

The matches dataset contains every football match played in the World Cup. Columns inside the dataset include which city was the match being played in, which team claimed victory or did the match result in a draw, win condition showing if the winning side need added extra time of penalties to win the game.

It also includes a summary of each World Cup held, the cups dataset contains columns winners, games, goals scored, and more.

**Comment by tracykteal** [comment]
Thank you so much for the idea! We used it for this week's TidyTuesday! 
https://twitter.com/tracykteal/status/1597385673539203078
