### ISSUE TITLE
James Beard Award Winners data

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [rfordatascience/tidytuesday#473]
Hello !

I put together a repo for James Beard Award Winners and a dataset. I have a data dictionary and an about section on the README page.

I scraped the website manually (rvest and ralger packages did not do the full scrape) and put the data in a CSV, and removed as many duplicates as I saw. 

If interested, [here is the repo](https://github.com/PythonCoderUnicorn/JamesBeardAward)

**Comment by lgibson7** [comment]
Hi @PythonCoderUnicorn. Thanks for submitting this issue. Would you be willing to submit the data set through a PR? You can find the instructions on how to do so [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/curated/template/instructions.md).
