### ISSUE TITLE
Data on French High Speed Train Delays

### ISSUE THREAD

**Issue by MathildeMousset** [rfordatascience/tidytuesday#48]
I found the data on high speed trains on the French train company (SNCF) open data site
They have several datasets:  

* between stations : https://frama.link/2Puw3PM1
* national summaries: https://frama.link/3cVHUhZL

The data on the stations (including the zipcode and the GPS coordinates are in another file): https://frama.link/Qh7-jkJ7 . I am afraid I have not been able to join both dataframes, my fuzzy joining and general data wrangling skills are not good enough yet, but maybe some people will be up to the challenge.

**Comment by jthomasmock** [comment]
Thanks for submitting this, I haven't done much with fuzzy-joining either, but great dataset! I'll likely focus on the same path you went down and leave the additional joining as an option.

**Comment by MathildeMousset** [comment]
You are welcome! Happy to contribute to this great challenge.
I think I need to aggressively filter "duplicates" in the station file (duplicates means that there are several stations for a given metropole, which may be separated by several kilometers, and DO NOT have the exact same name), and either make a custom function to try to select the best one, or decide that precision of the coordinates is not what really matters here (I have not been willing to take that road yet).

**Comment by jthomasmock** [comment]
Yah it seems like several other members tried and gave up on the joining, I think the between stations dataset is plenty to keep people busy!

**Comment by jthomasmock** [comment]
This was a great dataset!
