### ISSUE TITLE
English Monarchs & Marriages 

### ISSUE THREAD

**Issue by frankiethull** [rfordatascience/tidytuesday#480]
Dataset which lists monarch names, marriage age, and year of marriage. Some of the values are blank or include "(?)", which is a nice little puzzle. The data itself points to the history of 'child brides' in nobility but would like to see what others find. 

This was just an excuse for me to use the Quarto "gfm" template for a README. Thank you @jthomasmock!   

repo:
https://github.com/frankiethull/english_monarch_marriages

dataset: 
https://github.com/frankiethull/english_monarch_marriages/blob/main/english_monarch_marriages.csv

cleaning script: 
https://github.com/frankiethull/english_monarch_marriages/blob/main/cleaning_script.R

data source:
Data via Ian Mansfield, https://www.ianvisits.co.uk/articles/a-list-of-monarchs-by-marriage-6857/

**Comment by lgibson7** [comment]
Hi @frankiethull. Thanks for submitting this issue. Would you be willing to submit the data set through a PR? You can find the instructions on how to do so [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/curated/template/instructions.md).

**Comment by frankiethull** [comment]
hi @lgibson7  - Is this a new procedure? I can definitely test it out

**Comment by jonthegeek** [comment]
@frankiethull it's a new option, yes. We'd love to get the community more involved in maintaining tidytuesday!

**Comment by frankiethull** [comment]
@jonthegeek  - thanks for the info! & I love the idea... I started a github a few years ago just to get involved with this repo & learn git + github. Looking forward to trying the new option!
