### ISSUE TITLE
Google Reviews for Train Stations 2019-02-26

### ISSUE THREAD

**Issue by markswitajski** [rfordatascience/tidytuesday#49]
I manually created a spreadsheet which will allow you to merge the Google Review score (as of 2019-02-25) by name of the departure or arrival station. Just wanted to offer share in case others would find it useful! I'm new to Github so should you want the file, please let me know the best way to get it to you.

**note: I did this by hand and can't speak French very well, so take the scores with a grain of salt**

**Comment by jthomasmock** [comment]
My apologies for delay here - please link to the sheet and I'll upload to the data folder! Thanks!
