### ISSUE TITLE
Bird FeederWatch data

### ISSUE THREAD

**Issue by tracykteal** [rfordatascience/tidytuesday#490]
## Dataset proposed and link

Bird FeederWatch data
https://feederwatch.org/explore/raw-dataset-requests/

## Why is this an interesting dataset

"FeederWatch is a November-April survey of birds that visit backyards, nature centers, community areas, and other locales in North America." There's already a lot of examples of analyses on their 'explore' page. 
https://feederwatch.org/explore/ and there's a lot of options for analyses, including maps. Also, it could be neat to have citizen data analysis on citizen data. Plus birds!

## Is the dataset already clean?

The data does look clean and is available as csv.

## Are there good field descriptions available? 

Yes, there is a data dictionary available on their site. https://drive.google.com/file/d/1kHmx2XhA2MJtEyTNMpwqTQEnoa9M7Il2/view

## Are file sizes an issue?

There are multiple files, divided by year, and some of them are large (range is 380 MB – 1.3 GB), so this could be an issue.

## Any other notes or things to be aware of with this dataset?

Citizen data isn't always accurate, but the FeederWatch project has already done work to do the vetting that they can.

**Comment by jonthegeek** [comment]
Added in #493.
