### ISSUE TITLE
tt_load is not opening 2022 Week 52

### ISSUE THREAD

**Issue by ldanderson2015** [rfordatascience/tidytuesday#491]
Attempting to do tidytuesdayR::tt_load("2022-12-27") or ttload(2022, week = 52) both result in the following error:

Error in tt_check_date.date(x) : 
  2022-12-27 is not a date that has TidyTuesday data.
	Did you mean: 2022-12-20?

tidytuesdayR::tt_available() shows that week 52 is available. I was able to retrieve this data last week but am unable to do so now using tidytuesdayR due to the above error. Workaround is to use the direct links to the data from the readme.md file, but this makes the using the template a little wonky.

**Comment by jonthegeek** [comment]
Hmm. I can't replicate this error, but there IS an issue with the readme at https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/readme.md , so that might be related. I'm fixing that now. Thanks for the report!
