### ISSUE TITLE
Broken (Bird FeederWatch) data link

### ISSUE THREAD

**Issue by prvst** [rfordatascience/tidytuesday#496]
Hi, the Bird FeederWatch data link is broken:

https://github.com/rfordatascience/tidytuesday/blob/master/2022-01-10/readme.md

**Comment by jonthegeek** [comment]
Where does that link appear? It should be 2023, not 2022.

**Comment by prvst** [comment]
Main Readme.md file, scroll down to the Datasets section. I tried changing to 2023, but still did not work.

**Comment by jonthegeek** [comment]
It should be all set now. Thanks! That would have cascaded if we hadn't caught it this week!
