### ISSUE TITLE
arthistory

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rfordatascience/tidytuesday#499]
https://saralemus7.github.io/arthistory/

- The package is on CRAN: https://cran.r-project.org/web/packages/arthistory/index.html
- This package contains data that was used for Holland Stam’s thesis work, titled [Quantifying art historical narratives](https://doi.org/10.7924/r4dn48h0w). The data was collected to assess the demographic representation of artists through editions of Janson’s History of Art and Gardner’s Art Through the Ages, two of the most popular art history textbooks used in the American education system. In this package specifically, both artist-level and work-level data was collected along with variables regarding the artists’ demographics and numeric metrics for describing how much space they or their work took up in each edition of each textbook.
- Images:
  - Package logo: 
![image](https://user-images.githubusercontent.com/5965649/212497468-4f7940b4-4672-4b10-8c42-7935c4b8e1f5.png)
  - The covers images for the books:
    - https://www.amazon.com/Jansons-History-Art-Western-Tradition/dp/020568517X
    - https://www.amazon.com/Gardners-Art-Through-Ages-History/dp/1337630705/

My former students @saralemus7 and/or @hollandstam1 might have more to add as they developed the package.

**Comment by jonthegeek** [comment]
This is great, thank you!
