### ISSUE TITLE
Chipotle Orders

### ISSUE THREAD

**Issue by jthomasmock** [rfordatascience/tidytuesday#5]
https://www.nytimes.com/interactive/2015/02/17/upshot/what-do-people-actually-order-at-chipotle.html

https://github.com/TheUpshot/chipotle/blob/master/orders.tsv

**Comment by jthomasmock** [comment]
Slightly awkward dataset to work with - considering adding Calorie data to match the NYT article.

**Comment by jonthegeek** [comment]
Maybe point out that we have https://github.com/rfordatascience/tidytuesday/tree/master/data/2018/2018-09-04 if they want to try merging in that data.

**Comment by tracykteal** [comment]
Thanks @jthomasmock! I'm going through to close out older issues, so we can resurface datasets or point to updated ones.
