### ISSUE TITLE
28 years of European pharmaceutical development

### ISSUE THREAD

**Issue by MiqG** [rfordatascience/tidytuesday#503]
Hi!

Thanks for creating such an inspiring resource for data visualization!

I would like to share a dataset on the drugs approved by the European Medicine Agency that I gerated by scraping their website 3 years ago.

I have also written a short article on Medium doing some EDA on the dataset.

- dataset: https://github.com/MiqG/EMA-Data-Scratching-with-RSelenium/blob/master/drug_df_EMA.csv
- medium article: https://medium.com/towards-data-science/dissecting-28-years-of-european-pharmaceutical-development-3affd8f87dc0

**Comment by jonthegeek** [comment]
@MiqG Thanks for the submission! Can you verify that you followed https://www.ema.europa.eu/robots.txt when you scraped the data (or at least didn't do anything that you can now see is in violation of that)? They have some things that are disallowed so we like to make sure the dataset won't step on any toes. Thanks again!

**Comment by MiqG** [comment]
Hi @jonthegeek , thanks for pointing that out because I had no idea that existed. 

Looking back at the scripts I understand I only read what is publicly available at https://www.ema.europa.eu/medicines/field_ema_web_categories%253Aname_field/Human/ema_group_types/ema_medicine and do not go into any of the subfolders labeled as "Disallow".

Do you think its is okay then?

**Comment by jonthegeek** [comment]
@MiqG Excellent, thanks!

FYI, a lot of sites will have that `robots.txt` file in their root directory. It's good practice to check it to make sure you're following their rules before scraping data. It's good to hear that you didn't do anything they don't want, though!

**Comment by jonthegeek** [comment]
Images: 
https://miro.medium.com/v2/resize:fit:720/format:webp/1*wOVlCD80N9Sz_YDxSI7bXQ.png
https://miro.medium.com/v2/resize:fit:720/format:webp/1*yeMJwjUyTHeajdiTdm-QPg.png
