### ISSUE TITLE
Incorrect info in data dictionary for cat movement data (2023 week 5)

### ISSUE THREAD

**Issue by jacquietran** [rfordatascience/tidytuesday#507]
Kia ora Tidy Tuesday team!

For 2023 week 5, the data dictionary on the [readme](https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-01-31) page (and to be fair, from the [originating readme on the relevant Movebank page](https://www.datarepository.movebank.org/handle/10255/move.882)) has the following definition for the column `ground_speed`:

> The estimated ground speed provided by the sensor or calculated between consecutive locations. Units: m/s

However, in the data set itself, the number values for `ground_speed` are generally in the thousands. Unless the UK has some incredibly fast cats (or maybe the cats have self-reported their speeds 😉 😉 ), I think a reasonable guess is that the data set includes ground speed measured in mm / s.

I'll submit a pull request with updates to the data dictionary.

**Comment by jonthegeek** [comment]
FYI, if you say "Closes #507" (etc) in the initial PR message (rather than "tagging"), the issue auto-closes when the PR is merged. I probably could have fixed that in the PR but I thought replying with it would fix it 🙃

**Comment by jacquietran** [comment]
Ah yes, thanks for the tip @jonthegeek !
