### ISSUE TITLE
Bob Ross Paintings

### ISSUE THREAD

**Issue by frankiethull** [rfordatascience/tidytuesday#515]
This one interested me enough that I created a visualizer package based on the paintings! 

visualization repo/library: 
https://github.com/frankiethull/BobRossColors

dataset: shows all Bob Ross Paintings, the named colors he used, and a few other columns:
https://github.com/frankiethull/BobRossColors/blob/main/data/bob_ross_paintings.rda

data source: is a python package, someone already curated the paintings here: 
https://github.com/jwilber/Bob_Ross_Paintings/blob/master/data/bob_ross_paintings.csv

column descriptors: 
https://github.com/jwilber/Bob_Ross_Paintings 

Happy Trees, 
Frank

**Comment by jonthegeek** [comment]
Interesting! We did a Bob Ross dataset before... but it was by object, not color. This will offer participants an interesting chance to find correlations! Thanks!

**Comment by jonthegeek** [comment]
Notes for us:
Article: [Package github](https://github.com/frankiethull/BobRossColors)
Images: See article.

The link with column descriptors also has pngs of the paintings themselves!

**Comment by tracykteal** [comment]
Thanks @frankiethull and @jonthegeek! Used it for this week's dataset.

**Comment by frankiethull** [comment]
@tracykteal @jonthegeek thank you for accepting for this week's dataset. Also, appreciate you all sharing the other Bob Ross dataset, very cool!
