### ISSUE TITLE
Childcare costs

### ISSUE THREAD

**Issue by jthomasmock** [rfordatascience/tidytuesday#516]
source: https://www.dol.gov/agencies/wb/topics/childcare

Hat tip: https://twitter.com/jschwabish/status/1626597782491639810?s=46&t=avwSC7an3lwX3FH35u0gMA

**Comment by jonthegeek** [comment]
[dataset](https://www.dol.gov/sites/dolgov/files/WB/nationaldatabaseofchildcareprices.csv)

Images in src.

**Comment by jonthegeek** [comment]
Raw data is on the large side (~33 MB), but we can easily cut out some years to bring the size down.

Thanks, @jthomasmock ! I'm sure this is a topic you're thinking about a lot right now 😁
