### ISSUE TITLE
AfriSenti: A Twitter Sentiment Analysis Dataset in 14 African Languages

### ISSUE THREAD

**Issue by shmuhammad2004** [rfordatascience/tidytuesday#521]
# AfriSenti: A Twitter Sentiment Analysis Dataset in 14 African Languages

This week's data comes from [Twitter and is Available on this Repo](https://github.com/afrisenti-semeval/afrisent-semeval-2023). 

This [paper](https://arxiv.org/pdf/2302.08956.pdf) discusses data curation and benchmark sentiment classification in greater detail.

Credit: [Shamsuddeen Hassan Muhammad](@Shmuhammadd)

**Comment by jonthegeek** [comment]
To do (not necessarily all by you, @shmuhammad2004 , but I'm logging them so I know what's left):

- [ ] Extract 2 images from the article as erasonably-sized pngs to include in the announcement of the dataset. At least one of these should be a plot using the data.
- [ ] Write alt text descriptions for those two images.
- [ ] Clean the data into 1 or a few tidy csvs. These should be reasonably sized, so we might need to subset the data.

**Comment by jonthegeek** [comment]
Images:

- [pic1.png](https://github.com/afrisenti-semeval/afrisent-semeval-2023/blob/main/images/afrisenti-twitter.png):  "The AfriSenti logo. The continent Africa is incorporated into the A in AfriSenti, which is written in large, yellow-orange letters. Below that, Sentiment Analysis dataset for 14 African languages is written in smaller yellow letters."
- [pic2.png](https://raw.githubusercontent.com/afrisenti-semeval/afrisent-semeval-2023/main/afrisenti_languages.png):  "A bar chart of positive, negative, and neutral sentiment in tweets from 14 African languages. The languages are shown as abbreviations on the x axis, and the number of tweets range from 0 to 8000 on the y axis. Each language has 3 bars: blue for positive, red for negative, green for neutral. Hausa has the most tweets in all three sentiment categories, with over 7000 in each. Nigerian Pidgin has disproportionally more negative tweets than positive or neutral, and Yoruba has more positive or neutral tweets than negative."
