### ISSUE TITLE
FEMA data from NPR

### ISSUE THREAD

**Issue by sctyner** [rfordatascience/tidytuesday#54]
[NPR story](https://www.npr.org/2019/03/05/696995788/search-the-thousands-of-disaster-buyouts-fema-didnt-want-you-to-see) on who benefits most from FEMA relief. Data are [here](https://apps.npr.org/fema-table/assets/fema.csv). Part of their [investigation](https://www.npr.org/2019/03/05/688786177/how-federal-disaster-money-favors-the-rich), "How Federal Disaster Money Favors The Rich"

**Comment by tracykteal** [comment]
I'm going through past issues. Since this is now not a current dataset, I'm going to go ahead and close this out, but thank you so much for the idea @sctyner!
