### ISSUE TITLE
Variables Description Error | US Egg Production | Week 15,  2023-04-11 

### ISSUE THREAD

**Issue by AntonioAlegriaH** [rfordatascience/tidytuesday#545]
The **egg-production.csv** dataset describes **n_hens** as the number of **eggs** and vice versa.

 👇
**n_hens** | double | number of **eggs** produced by hens for a given month-type-process combo
**n_eggs** | double | number of **hens** producing eggs for a given month-type-process combo

Given that the numbers in **n_hens** are less than **n_eggs**, it makes me think that the description is misplaced.

**Comment by jonthegeek** [comment]
Doh, thanks!
