### ISSUE TITLE
US Tornado Dataset 1950-2021

### ISSUE THREAD

**Issue by evangower** [rfordatascience/tidytuesday#549]
### Seven decades of tornadic activity in the United States

[Dataset](https://www.kaggle.com/datasets/danbraswell/us-tornado-dataset-1950-2021) from Random Draw on Kaggle

This dataset was derived from a dataset produced by NOAA's Storm Prediction Center. The primary changes made to create this dataset were the deletion of some columns, change of some data types, and sorting by date. Tornado photo was taken by Ken Engquist on June 14, 2014 in Hildreth, Nebraska. It is from the NOAA photo library.

[Article](https://a-z-animals.com/blog/6-worst-tornadoes-in-the-united-states/) of The 7 Worst Tornadoes in the United States and the Destruction They Caused

My [notebook](https://www.kaggle.com/code/evangower/diving-into-us-tornado-data) and image ⬇️ from the data dive I did.

![tornadoes-by-state](https://user-images.githubusercontent.com/115375370/232334682-92c7b8fc-79a6-4813-bf44-daaed7f302e8.png)

**Comment by jonthegeek** [comment]
Used in #560. Thanks!
