### ISSUE TITLE
Instacart Orders

### ISSUE THREAD

**Issue by jjcole415** [rfordatascience/tidytuesday#55]
I ran across this dataset on Medium. It is a sample dataset of grocery orders from Instacart, the Uber Eats of grocery delivery.  Might be good for both data visualization as well as ML techniques.

Link to article: [https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2)
Link to dataset: [https://www.instacart.com/datasets/grocery-shopping-2017](https://www.instacart.com/datasets/grocery-shopping-2017)

@jthomasmock

**Comment by metatron1973** [comment]
![image](https://user-images.githubusercontent.com/80199202/209588815-83c76fce-83c2-42cb-a976-3a303745daee.png) the forensic audit should address the theft of wages here pretty ruthless to steal peoples money during holidays

**Comment by tracykteal** [comment]
I'm going through past issues. Since this data is no longer available, I'm going to go ahead and close this out, but thank you so much for the idea @jjcole415!
