### ISSUE TITLE
Historical Markers Database: US

### ISSUE THREAD

**Issue by jonthegeek** [rfordatascience/tidytuesday#574]
Dataset: Needs to be scraped from https://www.hmdb.org/geolists.asp?c=United%20States%20of%20America&u=
For this issue, just do the US; we could expand later to other places.

Article: The main website https://www.hmdb.org/ should do. They have lots of stories and analyses, but nothing super data-sciency.

I've checked robots.txt and their usage policies, and we're free to use them as long as we link back to hmdb.org, and keep attribution attached to any photos.

[![pic2](https://github.com/rfordatascience/tidytuesday/assets/33983824/cce08ebd-95e3-4b55-b75c-53150245f89a)](https://www.hmdb.org/PhotoFullSize.asp?PhotoID=157331)

Photographer: Clifton Patrick
Taken: June 14, 2011
Caption: Camp Wickham Marker
Submitted: June 14, 2011, by Clifton Patrick of Chester, NY, United States.

![pic1](https://github.com/rfordatascience/tidytuesday/assets/33983824/f03b3fab-aa0b-4d36-be13-f1222a6ec993)

**Comment by jmcastagnetto** [comment]
FYI, there is a big dataset of places of historical significance (code: HSTS) in the Geonames dataset (https://www.geonames.org/export/codes.html). The geonames ZIP for US, is about 66MB in size. 
Not comparable directly with the manually collated data from the source you mention, but related.

**Comment by joelnitta** [comment]
This website/database recently got a lot of use in this NPR article: https://www.npr.org/2024/04/21/1244899635/civil-war-confederate-statue-markers-sign-history
