### ISSUE TITLE
GPT Detector Data

### ISSUE THREAD

**Issue by jonthegeek** [rfordatascience/tidytuesday#582]
https://twitter.com/simonpcouch/status/1679158722352885762?s=19
https://github.com/simonpcouch/detectors

> I came across a paper "GPT Detectors Are Biased Against Non-Native English Writers" a couple weeks ago and took some time to tidy the source data + drop it into an #rstats data package. 

> You might enjoy poking at it as much as I have: github.com/simonpcouch/de…

**Comment by jonthegeek** [comment]
Closed in #583

**Comment by tracykteal** [comment]
Thanks @simonpcouch for the dataset!

**Comment by jmcastagnetto** [comment]
FYI, there is a published version of the article: https://www.cell.com/patterns/fulltext/S2666-3899(23)00130-7
