### ISSUE TITLE
Anime Dataset?

### ISSUE THREAD

**Issue by tamdrashtri** [rfordatascience/tidytuesday#59]
Hi, I found this anime list dataset is fascinating and I wonder if you could do a webcast on this. The link of the dataset is here: [](https://www.kaggle.com/aludosan/myanimelist-anime-dataset-as-20190204). 

It shows the ranking of anime based on different criteria.

**Comment by SimonLarsen** [comment]
In case someone else has trouble finding the link: https://www.kaggle.com/aludosan/myanimelist-anime-dataset-as-20190204.
