### ISSUE TITLE
Tidytuesday data submission - Roy Kent F**k count

### ISSUE THREAD

**Issue by deepshamenghani** [rfordatascience/tidytuesday#619]
Hi, I created this dataset for the Posit conference and Tom Mock recommended submitting it into Tidy Tuesday. I counted the number of times Roy Kent says f**k in each episode of Ted Lasso, and total f**k count of each episode, flags for dating and coaching, and imdb ratings. I turned it into this data package - https://github.com/deepshamenghani/richmondway .

The slides from the conference are here - https://deepshamenghani.github.io/posit_plotly_crosstalk/#/title-slide

**Comment by jonthegeek** [comment]
I love it! The full data dictionary is also wonderful! I'll fast-track this one!

**Comment by jonthegeek** [comment]
Closed via #621
Thanks!
