### ISSUE TITLE
Beach Volleyball Match Data

### ISSUE THREAD

**Issue by BigTimeStats** [rfordatascience/tidytuesday#62]
I publish a dataset of all matches played on the AVP and FIVB professional beach volleyball circuits:

https://github.com/BigTimeStats/beach-volleyball

There is some intro code to access and start querying the data. Would be happy to write additional posts to generate some visuals.

Some ideas to work more generally with the data:
- City/Country could be used to generate geographic maps and/or travel patterns from tournament to tournament or season to season
- Contains both the men's and women's tours along with demographic information
- Contains match stats data like aces, errors, kills, etc. that can be analyzed further

Let me know your thoughts.

**Comment by tracykteal** [comment]
Thanks @BigTimeStats! This data has continued to be updated through 2022, so is still a good option.

**Comment by jonthegeek** [comment]
Used for [2020-05-19](https://tidytues.day/2020/2020-05-19).
