### ISSUE TITLE
Data on American Idol 

### ISSUE THREAD

**Issue by kkakey** [rfordatascience/tidytuesday#620]
I web scraped songs competed on American Idol from seasons 1-18, along with info on the finalists, seasons, and episode ratings.

- [`songs_all.csv`](https://github.com/kkakey/American_Idol/blob/main/Songs/songs_all.csv) - songs that contestants sang and competed with on American Idol from seasons 1-18
- [`finalists.csv`](https://github.com/kkakey/American_Idol/blob/main/metadata/finalists.csv) - information on top contestants, including birthday, hometown, and description
- [`seasons.csv`](https://github.com/kkakey/American_Idol/blob/main/metadata/seasons.csv) - season-level information, including season winner, runner-up, release dates, and judges
- [`auditions.csv`](https://github.com/kkakey/American_Idol/blob/main/metadata/auditions.csv) - audition, cities, dates, and venues
- [`elimination_chart.csv`](https://github.com/kkakey/American_Idol/blob/main/metadata/elimination_chart.csv) - eliminations by week
- [`ratings.csv`](https://github.com/kkakey/American_Idol/blob/main/metadata/ratings.csv) - episode ratings and views.

Code, data, and data dictionaries: https://github.com/kkakey/American_Idol

**Comment by jonthegeek** [comment]
Used via #708.
