### ISSUE TITLE
R-Ladies Chapters Events

### ISSUE THREAD

**Issue by Fgazzelloni** [rfordatascience/tidytuesday#632]
Please fill out as much of this information as you can! 

- **Dataset name:** rladies_chapters
- **Dataset download URL:** [https://github.com/Fgazzelloni/RLadies-Chapters-Making-Talks-Work-for-Diverse-Audiences/blob/main/data/rladies_chapters.csv](https://github.com/Fgazzelloni/RLadies-Chapters-Making-Talks-Work-for-Diverse-Audiences/blob/main/data/rladies_chapters.csv)
- **Article that demonstrates the dataset:** R-Ladies Global is an inspiring story of community, empowerment, and diversity in the field of data science. Founded by Gabriela de Queiroz, R-Ladies began as a grassroots movement with a simple mission: to promote gender diversity in the R programming community and provide a welcoming space for women and gender minorities to learn, collaborate, and excel in data science. [R-Ladies Global Website](rladies.org)
- **Image 1 URL:** [top_rladies_chapters](https://fgazzelloni.quarto.pub/rladies_chapters_talks/images/top_rladies_chapters.png)
- **Image 1 ALT text:** top_rladies_chapters
- **Image 2 URL:** [rladies_chapters_distrib](https://fgazzelloni.quarto.pub/rladies_chapters_talks/images/rladies_chapters_distrib.png)
- **Image 2 ALT text:** rladies_chapters_distrib

**Cleaning script:**

```r
library(tidyverse)
library(jsonlite)
data <- jsonlite::fromJSON('https://raw.githubusercontent.com/rladies/meetup_archive/main/data/events.json')

chapters <- data %>%
  select(1,2,3,7,8)%>% 
  rename(chapter=group_urlname)%>%
  mutate(location=ifelse(location=="Online event","online","inperson"),
         title=sub(".*-- ","",title),
         title=gsub("\\s*\\([^\\)]+\\)","",title)) %>%
  filter(!str_detect(title,regex("canceled|cancelled",ignore_case=T)),
         !chapter%in%c("RLadiesJeddah","muhq_deleted@4633@rladies-ushuaia",
                      "muhq_deleted@9919@notopic@508502","notopic@544550"))%>%
  arrange(desc(date))%>%
  filter(year(date)<2024)%>%
  mutate(year=year(date))

# to download the n. of attendees
library(meetupr)
# meetupr::get_event_attendees("event-id")

id <- rladies_chapters$id
id1 <- id[1:25]

attendees <- function(id) {
  dat<- meetupr::get_event_attendees(id)%>%
   dim()
    dat[1]
}

mylist <- lapply(id1,attendees)

first25 <- mylist%>%unlist()
first25_events <- rladies_chapters[1:25,]%>%
  cbind(first25)
```

**Data dictionary:**

|variable            |class     |description         |
|:-------------------|:---------|:-------------------|
|id            |double     |event id         |
|chapter            |character     |rladies chapter name         |
|title            |character     |event title         |
|date            |date     |event date         |
|location            |character     |event location if online or in person         |
|year            |double     |event year        |

**Comment by tracykteal** [comment]
Dataset for the week of 2023-11-21. Thanks!
