### ISSUE TITLE
Air Pollution

### ISSUE THREAD

**Issue by soroosj** [rfordatascience/tidytuesday#65]
Might be interesting for the group to analyze air pollution.  I discovered the World Health Organization seems to publish air quality readings for cities across the globe.    

[WHO Site](https://www.who.int/airpollution/data/cities/en/) , [database](https://www.who.int/airpollution/data/aap_air_quality_database_2018_v14.xlsx?ua=1) and [article](https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health) as potential starting points.

**Comment by arlugones** [comment]
One of the main components of air pollution is the study of particulate matter with size less than 2.5 microns (pm 2.5). Data on measures from several stations in Quito, Ecuador are recorded by the Environment Secretary (Secretaría del Ambiente in spanish).
Data can be downloaded from [data pm 2.5](http://www.quitoambiente.gob.ec/ambiente/images/Secretaria_Ambiente/red_monitoreo/informacion/PM2.5.rar)
Some other related records can be found in each category at [Secretaría del Ambiente - Historical data](www.quitoambiente.gob.ec/ambiente/index.php/datos-horarios-historicos)

**Comment by tracykteal** [comment]
I'm going through past issues. Since this dataset is now not available, I'm going to go ahead and close this out, but thank you so much for the idea @soroosj and @arlugones!
