### ISSUE TITLE
stuff around null island (lat = lng = 0)

### ISSUE THREAD

**Issue by jillson** [rfordatascience/tidytuesday#653]
Not sure how systemic this is and whether it's a feature (as in reminding people to filter out bad data), but for example:

https://github.com/rfordatascience/tidytuesday/blob/master/data/2019/2019-08-20/nuclear_explosions.csv has multiple rows with lat/lng that is incorrectly specified as zero.

One specific example: 19850618,1985,85034,USSR,TUYMEN RUSS,MTM,0,0,0,0,0,2.5,2.5,PNE,BENZOL,SHAFT
Using wikipedia (https://en.wikipedia.org/wiki/1985_Soviet_nuclear_tests) suggests this (Benzol) should be at 60.6°N 72.7°E

If this isn't intentional, probably could do a regex filter or awk would be something like `awk -F, '$7 != 0 || $8 != 0'` should do it for at least CSV that don't have embedded commas

**Comment by jonthegeek** [comment]
As a rule we don't systematically change old datasets, since it can break people's code. Thanks for the information! We'll watch out for such errors in future datasets!
