### ISSUE TITLE
super_hero_powers.csv

### ISSUE THREAD

**Issue by gkaramanis** [rfordatascience/tidytuesday#66]
https://www.kaggle.com/claudiodavi/superhero-set#super_hero_powers.csv

> This data was collected in June/2017 from superherodb and not updated since, so it may not be up to date. There are two datasets here. The first one lists the characteristics of every super hero found on my source, the second contains information about every superpower and lists if they are present in any given hero.

**Comment by tracykteal** [comment]
I'm going through past issues. Since this is now not a current dataset, I'm going to go ahead and close this out, but thank you so much for the idea @gkaramanis!
