### ISSUE TITLE
Trash Wheel Collection Data: Unexpected total rows detected

### ISSUE THREAD

**Issue by AntonioAlegriaH** [rfordatascience/tidytuesday#668]
I noticed three observations that had unusually high values for the Weight: Gwynnda, Professor, and the Captain

```markdown
1 | Gwynnda Trash Wheel |653.00 |
2 | Professor Trash Wheel | 235.31 |
3 | Captain Trash Wheel | 37.35 |
```
Afterward, I calculated the sum of the weights, excluding these outliers. It appears that these outliers represent the total weight.

```markdown
Name                       n
  <chr>                  <dbl>
1 Captain Trash Wheel     37.4
2 Gwynnda Trash Wheel    653. 
3 Professor Trash Wheel  235. 
```
In the original spreadsheet, I found a row at the bottom that sums up all the variables. It seems the cleaning script missed removing the total row at the bottom of the original spreadsheet, suggesting it might not be intended to be included.

**Comment by tracykteal** [comment]
Thank you so much! You're correct, I removed that row from Mister, but not Captain, Gwynnda or Professor. I'll put in a PR with a fix.
