### ISSUE TITLE
Great American Coffee Taste Test dataset

### ISSUE THREAD

**Issue by miguelangel43** [rfordatascience/tidytuesday#672]
Survey data about America's coffee taste preferences

- **Dataset name:** Great American Coffee Taste Test
- **Dataset download URL:** https://bit.ly/gacttCSV
- **Article that demonstrates the dataset:** https://www.youtube.com/watch?v=bMOOQfeloH0

**Comment by jonthegeek** [comment]
Used in #688. Thanks!
