### ISSUE TITLE
Make Dataset Submissions More Prominent

### ISSUE THREAD

**Issue by jonthegeek** [rfordatascience/tidytuesday#720]
Add information more prominently on the main page + weekly pages about submitting a dataset (as a PR). Make it clearer that we very much would love submissions, and that it's probably not a lot harder to submit your own dataset vs telling us about it.

**Comment by lgibson7** [comment]
- I think perhaps even having an announcement in the Slack on a regular cadence (every 2-4 weeks) would be good. Could be posted in the Tidy Tuesday channel or Announcements.
- Also, maybe a small blurb at the end of your social media posts. Something along the lines of "Have a data set you'd like to see in an upcoming Tidy Tuesday? Propose it here! Oh, and don't forget to give yourself credit."

**Comment by jonthegeek** [comment]
We post the datasets in the tidytuesday channel on Slack, so I don't think we necessarily need another thing there. And I killed almost all of the recurring messages because they annoyed people (and thus eventually got ignored). Maybe aim more to make it part of the culture; if someone mentions a cool dataset, encourage them to share it on TT.

**Comment by lgibson7** [comment]
That makes sense. Good call.
