### ISSUE TITLE
Crediting curators on social media

### ISSUE THREAD

**Issue by lgibson7** [rfordatascience/tidytuesday#732]
Suggestion: Create file within curated folder for external curators to provide their social media handles and full names.

I think knowing your name will show up on posts in LinkedIn will really incentivize curating a dataset.

**Comment by lgibson7** [comment]
Just realized this was added to meta.yaml

**Comment by jonthegeek** [comment]
I added the metadata, but haven't yet updated the auto-posters (over in https://github.com/rfordatascience/ttpost) to actually USE that data. It's on the to-do!

**Comment by lgibson7** [comment]
Awesome. Sounds good.

I would like to help workshop the text of the posts. Which files contain the actual verbiage that's posted? I think "Want to help?" should be one of the bullets following the explanation of what Tidy Tuesday is.
