### ISSUE TITLE
International Mathematical Olympiad (IMO) Data

### ISSUE THREAD

**Issue by havishak** [rfordatascience/tidytuesday#738]
Please fill out as much of this information as you can!

- [X] This dataset has not already been used in TidyTuesday.
- [X] The dataset will (probably) be less than 20MB when saved as a tidy CSV.
- [X] I can imagine a data visualization related to this dataset.

- [X] **title:** IMO Data
- [X] **article:** An example of the dataset being used, such as a blog post or a README about the dataset.
  - [X] **title:** Global Map of 2024 International Mathematical Olympiad Scores
  - [X] **url:** https://www.voronoiapp.com/maps/-Global-Map-of-2024-International-Mathematical-Olympiad-Scores-1875
- [ ] **data_source:** A source where the dataset can be downloaded.
  - [ ] **title:** Will have to scrape
  - [ ] **url:** https://www.imo-official.org/year_country_r.aspx?year=2024
- [X] **images:** One or more images related to the dataset. For each image, provide:
  - [X] **file:** https://www.voronoiapp.com/_next/image?url=https%3A%2F%2Fcdn.voronoiapp.com%2Fpublic%2Fimages%2Fvoronoi--Global-Map-of-2024-International-Mathematical-Olympiad-Scores-20240723225543.webp&w=1200&q=75
  - [X] **alt:** A map of the world colored according to 2024 IMO rank and total team scores. A total of 107 countries participated and non-participating are shown in grey. US was ranked 1 with a score of 192, followed by China with a score of 190. 

Team and individual data are available from 1959-present but will have to be scraped.

**Comment by havishak** [comment]
Hi, I scraped and curated this dataset - see pull request. Thanks!

**Comment by lgibson7** [comment]
Thanks @havishak! You can also use the phrase "closes {number}" or "fixes {number}" in the PR body so you don't have to manually close the issue. See here for more: https://code-review.tidyverse.org/author/submitting.html#closes
