### ISSUE TITLE
Sea ice extent Tidy Tuesday?

### ISSUE THREAD

**Issue by SwampThingPaul** [rfordatascience/tidytuesday#74]
Hi all, I was curious if there was ever a TidyTuesday that focused on sea-ice extent? Like the example below? The idea came from a tweet I shared from [Zack Labe](https://twitter.com/ZLabe/status/1135561951205941249). Not sure if the dataset is readily available but would definitely make for a great TidyTuesday. 

![Beaufort-Chukchi](https://pbs.twimg.com/media/D8JS46wUEAEFlZT.jpg)

**Comment by gtm19** [comment]
There is data for this on the [National Snow and Ice Data Center website](https://nsidc.org/). It includes shapefiles as well.
