### ISSUE TITLE
Opportunity Insights data

### ISSUE THREAD

**Issue by havishak** [rfordatascience/tidytuesday#741]
- [X] This dataset has not already been used in TidyTuesday.
- [X] The dataset will (probably) be less than 20MB when saved as a tidy CSV.
- [X] I can imagine a data visualization related to this dataset.

- [X] **title:** Opportunity Insights Data (contains multiple dataset)
- [X] **article:** 
  - [X] **title:**  Economic diversity and student outcomes at City College of New York
  - [X] **url:** https://www.nytimes.com/interactive/projects/college-mobility/city-college-of-new-york
- [X] **data_source:** 
  - [X] **title:** Opportunity Insights Data Repository
  - [X] **url:** https://opportunityinsights.org/data/ (there's also a Github repo)
 The one in the article is 'College-Level Data for 139 Selective American Colleges '
- [X] **images:** One or more images related to the dataset. For each image, provide:
  - [X] **file:** https://www.nytimes.com/interactive/projects/college-mobility/city-college-of-new-york
  - [X] **alt:** Shows parent income for students attending City College of New York. 23% of students who attend City College of New York have parents in the bottom 20% of the income quantile whereas 15% of students have parents in the top 20%.

- [ ] **cleaning_script:** A script to fetch and clean the data, resulting in one or more data.frames (or equivalent structures) that can be saved as CSVs.
It's already clean.

**Comment by lgibson7** [comment]
@jonthegeek it looks like this one may be ready to go. Per @havishak, no cleaning script is needed.

**Comment by havishak** [comment]
Thanks @jonthegeek for completing the PR request for this! 
After playing with the dataset for TidyTuesday, I realized that the data in the NYT article had more variables, so my guess is that multiple datasets were merged to create those visuals. Sorry for any confusion.

**Comment by jonthegeek** [comment]
@havishak That's fine! We had enough data for people to make visualizations, even if it wasn't ALL of the data. If you think it would be a good idea, feel free to open another issue for other aspects of that dataset, and/or submit a PR! We probably won't go back to it RIGHT away, but it wouldn't hurt to revisit it if there's more to explore!
