### ISSUE TITLE
Shakespeare scripts dataset

### ISSUE THREAD

**Issue by nrennie** [rfordatascience/tidytuesday#745]
Please consider submitting this dataset as a pull request! See https://github.com/rfordatascience/tidytuesday/blob/master/.github/pr_instructions.md to learn how.
Please fill out as much of this information as you can!

- [x] This dataset has not already been used in TidyTuesday.
- [x] The dataset will (probably) be less than 20MB when saved as a tidy CSV.
- [x] I can imagine a data visualization related to this dataset.

- [x] **title** The Plays of William Shakespeare
- [x] **article:** GitHub repository
  - [x] **title:** Shakespeare data
  - [x] **url:** https://github.com/nrennie/shakespeare
- [x] **data_source:** GitHub repository, originally from https://shakespeare.mit.edu/
  - [x] **title:** Shakespeare data
  - [x] **url:** https://github.com/nrennie/shakespeare
- [x] **images:** One or more images related to the dataset. For each image, provide:
  - [x] **file:** https://github.com/nrennie/shakespeare/blob/main/plots/hamlet.png
  - [x] **alt:** Bar chart of the number of lines of dialogue per scene in Hamlet.

- [x] **cleaning_script:** See https://github.com/nrennie/shakespeare/tree/main/R 

- [x] **data_dictionary:** A description of each column in the dataset, including the column name, the data type of the column, and a description of the column.

|variable         |class     |description         |
|:--------------|:---------|:-------------------|
|act                 |character    |Act number                         |
|scene             |character    |Scene number                    |
|character       |character    |Name  of character speaking  |
|dialogue        |character    |Text of dialogue                  |
|line_number  |numeric      |Dialogue line number         |

**Comment by jonthegeek** [comment]
@nrennie Thanks! Would you be interested in preparing this per https://github.com/rfordatascience/tidytuesday/blob/master/.github/pr_instructions.md ? We've had you on our list of people to try to recruit for submissions once those instructions have been tested a bit 😊

**Comment by nrennie** [comment]
@jonthegeek Yes, no problem - I'll make a PR :)

**Comment by jonthegeek** [comment]
Closed via #748.
