### ISSUE TITLE
94 years of Christmas Bird Count data for Hamilton, Ontario

### ISSUE THREAD

**Issue by sharleenw** [rfordatascience/tidytuesday#76]
Every year around Christmas time, since 1921, birdwatchers in the Hamilton area of Ontario have gone out and counted all the birds they see or hear in a day.

They have been carefully recording this data, and the raw data is available through the website of  [Bird Studies Canada](https://www.birdscanada.org/index.jsp) (twitter handle: @BirdsCanada).

[On my blog](https://sharleenw.rbind.io/post/hamilton_cbc_part_1/hamilton-christmas-bird-count-part-1/), I cleaned up the data (and in later posts, visualized it).

There are lots of interesting trends to look at and it would be a fun dataset for a #TidyTuesday!

I've attached the cleaned data to this issue.

[hamilton_christmas_bird_count_data_cleaned.txt](https://github.com/rfordatascience/tidytuesday/files/3253659/hamilton_christmas_bird_count_data_cleaned.txt)

**Comment by jthomasmock** [comment]
So excited for this!

**Comment by chrisfs** [comment]
Why are there NAs in the hours field in the earlier years ? did they simply not record the hours spent ?

**Comment by sharleenw** [comment]
I looked at the documentation (http://netapp.audubon.org/cbcobservation/#) but it didn't really say.

I would imagine that the NAs mean that the hours spent were either not recorded or not submitted to this database.
