### ISSUE TITLE
Meteorite Landings

### ISSUE THREAD

**Issue by malinfax** [rfordatascience/tidytuesday#78]
> This comprehensive data set from The Meteoritical Society contains information on all of the known meteorite landings. 

[https://data.nasa.gov/Space-Science/Meteorite-Landings/gh4g-9sfh/data](url)

For understanding meteorite classifications, the wikipage is pretty helpful: [https://en.wikipedia.org/wiki/Meteorite_classification](url)

**Comment by jthomasmock** [comment]
Using this week thanks!
