### ISSUE TITLE
more CA fire damage data available

### ISSUE THREAD

**Issue by OneGneissGuy** [rfordatascience/tidytuesday#8]
I've got more historical data for fires that occurred in CAL FIRE's jurisdiction, including NUMBER OF FIRES , ACRES BURNED and DOLLAR DAMAGE form 1933 to 2016. 
Repo [here](https://github.com/OneGneissGuy/CA-fires)
Data file available [here](https://github.com/OneGneissGuy/CA-fires/blob/master/data/ca-fire-incidents.csv)

**Comment by jthomasmock** [comment]
Added to week 21
