### ISSUE TITLE
Hypoxia data set

### ISSUE THREAD

**Issue by cooknl** [rfordatascience/tidytuesday#9]
I am a glider pilot, and when gliders go above 14,000 feet, the pilot is required to have a supplemental oxygen source.

The magazine of the Soaring Society of America (SSA), _Soaring_, recently published an article about the lack of oxygen and/or carbon dioxide during flight, and the table caught my eye.

I received permission from the author and editor to post the article and "crowdsource" different means of presenting the data, which could include alternative tabular representations or other more visual means.

Here is the article in full. [Hypoxia Article proof.pdf](https://github.com/rfordatascience/tidytuesday/files/2343596/Hypoxia.Article.proof.pdf)

I've transcribed the Table 1 data into a comma-separated text file, since the table is an image in the article. [table1.txt](https://github.com/rfordatascience/tidytuesday/files/2343598/table1.txt)

The author, the editor, and I are very interested in the products of everyone's imaginations! SSA is a non-profit, the author was not paid for his work, and the table originated from Guyton & Hall: Textbook of Medical Physiology, 12th ed. Attribution is all that is requested.

Johnson, D. (2018, August). Hypoxia, Hyperventilation, and Supplemental Oxygen Systems. Soaring, 19-27.

Hall, J. E., & Guyton, A. C. (2011). Guyton and Hall Textbook of Medical Physiology, 12e. Philadelphia: Elsevier Saunders.

**Comment by jthomasmock** [comment]
Cool! Let me think of how to write this out and maybe use for next week. Thanks for submitting!

**Comment by cooknl** [comment]
Awesome! One other thing to mention would be the increase in issues military aviators have had recently with breathing. This is an area of current concern.

**Comment by cooknl** [comment]
Awesome! One other thing to mention would be the increase in issues military aviators have had recently with breathing. This is an area of current concern.
